alias -s MD=vi # 在命令行直接输入后缀为 MD 的文件名，会在 TextMate 中打开
alias -s bz2='tar -xjvf'
alias -s c=vi
alias -s data=vi # 在命令行直接输入后缀为 md 的文件名，会在 TextMate 中打开
alias -s gz='tar -xzvf'
alias -s html=vi # 在命令行直接输入后缀为 html 的文件名，会在 TextMate 中打开
alias -s java=vi
alias -s js=vi
alias -s log=vi # 在命令行直接输入后缀为 log 的文件名，会在 TextMate 中打开
alias -s md=vi # 在命令行直接输入后缀为 md 的文件名，会在 TextMate 中打开
alias -s py=vi # 在命令行直接输入 python 文件，会用 vim 中打开，以下类似
alias -s rb=vi # 在命令行直接输入 ruby 文件，会在 TextMate 中打开
alias -s sql=vi # 在命令行直接输入后缀为 md 的文件名，会在 TextMate 中打开
alias -s tgz='tar -xzvf'
alias -s txt=vi
alias -s xml=vi # 在命令行直接输入后缀为 xml 的文件名，会在 TextMate 中打开
alias -s yml=vi # 在命令行直接输入后缀为 md 的文件名，会在 TextMate 中打开
alias -s zip='unzip'
